### ISSUE TITLE
Normal user unable to add own dataset to group/topic

### ISSUE THREAD

**Issue by mdelcambre** [codefordc/opendatadc#16]
I am able to successfully upload and update a dataset both with the website and the api. However I do not see a clear way for me to add this dataset to a group/topic.

In this case I have http://data.codefordc.org/dataset/wmata-metro-disruptions but am unable to find a way to add it to the 'Transportation' group/topic. 

I suspect this is a permission issue as CKAN typically just removes (instead of disabling) action/buttons you don't have access to.

**Comment by mkalish** [comment]
I'm not seeing any setting for disabling/enabling adding sets to group.  Just to confirm, this is why I see when I'm the on the dataset.

<img width="1049" alt="screen shot 2016-10-22 at 1 56 24 pm" src="https://cloud.githubusercontent.com/assets/1225895/19621413/6804df2e-985f-11e6-93db-e53139b88639.png">

Is the tab no there or the button to add it to a group?

**Comment by mdelcambre** [comment]
Yeah there is nothing on my end:

![image](https://cloud.githubusercontent.com/assets/117248/19647475/3dde8aa6-99cc-11e6-82b2-b8cbffc719f6.png)

The manage tab doesn't have anything either.

**Comment by mkalish** [comment]
Thanks for the update... I'll track down the flag tonight.

**Comment by mdelcambre** [comment]
Yeah I didn't have the button to add /remove on that tab. Can confirm later
tonight to see if that has changed

**Comment by mkalish** [comment]
I (think) this is fixed.  Looked like you were added as a member rather than editor, meaning you didn't have any permissions.  Let me know if you're good to go.

**Comment by mdelcambre** [comment]
Oddly, still the same.
I had figured that I was in a odd category for joining the site early.

**Comment by mkalish** [comment]
d
